name: Daily Notion Comment Sync

on:
  # 定时触发 - 每日凌晨3点（Brisbane时间，UTC 17:00）
  schedule:
    - cron: '0 17 * * *'
  
  # 手动触发 - 这是关键配置
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        required: false
        default: 'production'
        type: choice
        options:
        - production
        - staging
      force_run:
        description: 'Force run even if no new data'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Notion Comment Sync
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        REFERENCE_DATABASE_ID: ${{ secrets.REFERENCE_DATABASE_ID }}
        TARGET_DATABASE_ID: ${{ secrets.TARGET_DATABASE_ID }}
        ACTION_DATABASE_ID: ${{ secrets.ACTION_DATABASE_ID }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      run: node src/main.js
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs-${{ github.run_number }}
        path: |
          *.log
          logs/
        retention-days: 7