name: Auto Sync Notion Comments

on:
  schedule:
    # 每6小时执行一次同步
    - cron: '0 */6 * * *'
  
  # 手动触发
  workflow_dispatch:
    inputs:
      force_sync:
        description: '强制同步（忽略时间间隔）'
        required: false
        default: false
        type: boolean

  # 推送到主分支时也执行
  push:
    branches: [ main, master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file
      run: |
        echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env
        echo "REFERENCE_DATABASE_ID=${{ secrets.REFERENCE_DATABASE_ID }}" >> .env
        echo "REFERENCE_DATABASE_URL=${{ secrets.REFERENCE_DATABASE_URL }}" >> .env
        echo "TARGET_DATABASE_ID=${{ secrets.TARGET_DATABASE_ID }}" >> .env
        echo "LOG_LEVEL=info" >> .env
        echo "SYNC_INTERVAL=3600000" >> .env
        
    - name: Run sync
      run: npm run sync
      
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs
        path: |
          *.log
          logs/
        retention-days: 7
        
    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#notifications'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
