name: Verify Organization Secrets

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Show detailed output'
        required: false
        default: true
        type: boolean

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Verify Organization Secrets
      run: |
        echo "🔍 Verifying Organization Secrets..."
        echo "=================================="
        
        # Check each secret
        secrets=(
          "NOTION_API_TOKEN"
          "REFERENCE_DATABASE_ID" 
          "TARGET_DATABASE_ID"
          "ACTION_DATABASE_ID"
          "SMTP_HOST"
          "SMTP_PORT"
          "SMTP_USER"
          "SMTP_PASS"
          "EMAIL_TO"
          "EMAIL_FROM"
        )
        
        all_good=true
        
        for secret in "${secrets[@]}"; do
          if [ -n "${!secret}" ]; then
            echo "✅ $secret: Set (${#!secret} characters)"
          else
            echo "❌ $secret: Missing"
            all_good=false
          fi
        done
        
        echo "=================================="
        if [ "$all_good" = true ]; then
          echo "🎉 All organization secrets are properly configured!"
          echo "✅ Ready to run the main workflow"
        else
          echo "⚠️  Some secrets are missing. Please check organization settings."
          echo "📋 Go to: https://github.com/ericmao2008/settings/secrets/actions"
        fi
        
    - name: Test Notion API Connection
      if: env.NOTION_API_TOKEN != ''
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_TOKEN }}
      run: |
        echo "🔗 Testing Notion API connection..."
        # Simple API test
        response=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer $NOTION_API_TOKEN" \
          -H "Notion-Version: 2022-06-28" \
          "https://api.notion.com/v1/users/me")
        
        if [ "$response" = "200" ]; then
          echo "✅ Notion API connection successful"
        else
          echo "❌ Notion API connection failed (HTTP $response)"
        fi
        
    - name: Test SMTP Configuration
      if: env.SMTP_HOST != '' && env.SMTP_USER != ''
      env:
        SMTP_HOST: ${{ secrets.MAIL_HOST }}
        SMTP_PORT: ${{ secrets.MAIL_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      run: |
        echo "📧 Testing SMTP configuration..."
        echo "Host: $SMTP_HOST"
        echo "Port: $SMTP_PORT"
        echo "User: $SMTP_USER"
        echo "✅ SMTP configuration looks good"
